config/routes.rb
Rails.application.routes.draw do
  get 'article_query_logs/create'
  get 'article_query_logs/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :article_query_logs, only: [:create, :index]
  get 'dashboard', to: 'ranking_words#index'
  get '/', to: 'article_query_logs#index'
  post 'query', to: 'article_query_logs#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article_query_log.rb
class ArticleQueryLog < ApplicationRecord
  validates :query, presence: true
  validates :ip, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/article_query_logs_controller.rb
class ArticleQueryLogsController < ApplicationController
  protect_from_forgery with: :null_session

  def create
    @search_log = ArticleQueryLog.new(search_params)
    @search_log.ip = request.remote_ip

    if @search_log.save
      render json: {
        status: 'Success'
      }, status: :created
    else
      render json: {
        errors: @search_log.errors.full_messages
      }, status: :unprocessable_entity
    end
  end

  def index
    @search_trends = ArticleQueryLog.all
    # render json: @search_trends
  end

  private

  def search_params
    params.require(:search_log).permit(:query)
  end
end

app/controllers/ranking_words_controller.rb
class RankingWordsController < ApplicationController
  def index
    queries = ArticleQueryLog.all.map(&:query)
    ranker = RankKeywords.new(queries)
    ranker.rank_keywords
    @ranked_keywords = ranker.keyword_data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_query_logs_helper.rb
module ArticleQueryLogsHelper
end

app/helpers/ranking_words_helper.rb
module RankingWordsHelper
end

app/views/article_query_logs/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Search Analytics</title>
  <%= javascript_include_tag 'application', type: 'importmap' %>
  <%= javascript_include_tag 'controllers/searchEngine', type: 'module' %>
  <%= stylesheet_link_tag 'home/index' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <main class="main-window">
    <h1 class="header">Realtime Search Box</h1>
    <div class="search-bar">
      <input type="text" id="search-input" placeholder="Type to search...">
      <div id="search-results"></div>
    </div>
  </main>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchEngine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ranking_words/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Search Analytics</title>
    <%= javascript_include_tag 'application', type: 'importmap' %>
    <%= javascript_include_tag 'controllers/searchEngine', type: 'module' %>
    <%= stylesheet_link_tag 'home/index' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <main class="dashboard">
    <h1 class="dashboard-header">Keyword Rankings</h1>
    <div class="table-content">
    <table>
      <thead>
        <tr>
          <th>Keyword</th>
          <th>Count</th>
          <th>Queries</th>
        </tr>
      </thead>
      <tbody>
        <% @ranked_keywords.each do |data| %>
          <tr>
            <td><%= data[:keyword] %></td>
            <td><%= data[:count] %></td>
            <td>
              <ul>
                <% data[:queries].each do |query| %>
                  <li><%= query %></li>
                <% end %>
              </ul>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </main>
  </body>
</html>

app/views/shared/_navbar.html.erb
<%= stylesheet_link_tag 'home/index' %>
<nav class="nav-bar">
  <div class="left">
    <ul class="left-elem">
      <%= link_to 'Logo', dashboard_path, class: "nav-elem"%>
    </ul>
  </div>
  <div class="right">
    <ul class="right-elem">
      <%= link_to 'Search', article_query_logs_index_path, class: "nav-elem" %>
      <%= link_to 'Trending Searches', dashboard_path, class: "nav-elem" %>
    <ul>
  </div>
</nav>